### ISSUE TITLE
Not able to build package

### ISSUE THREAD

**Issue by hrabalvojta** [dahendel/terraform-provider-awx2#1]
Hi, 
I am not able to get/build it:
`
$ go get gitlab.com/dhendel/terraform-provider-awx
`
`
dhendel/terraform-provider-awx/awx/resource_job_template.go:38:5: cannot use validation.StringInSlice([]string literal, true) (type "github.com/hashicorp/terraform/helper/schema".SchemaValidateFunc) as type "gitlab.com/dhendel/terraform-provider-awx/vendor/github.com/hashicorp/terraform/helper/schema".SchemaValidateFunc in field value`
`
dhendel/terraform-provider-awx/awx/resource_job_template.go:87:5: cannot use validation.IntInSlice([]int literal) (type "github.com/hashicorp/terraform/helper/schema".SchemaValidateFunc) as type "gitlab.com/dhendel/terraform-provider-awx/vendor/github.com/hashicorp/terraform/helper/schema".SchemaValidateFunc in field value
`

Update of README.md would be nice.

**Comment by dahendel** [comment]
I will get that updated. Apologies. This uses go modules so you will need to enable go modules and I will also push some pre-built binaries today.

**Comment by dahendel** [comment]
@hrabalvojta  I updated the README and fixed the error that was getting thrown.  Also, setup goreleaser to publish builds. Let me know if you can't get it built locally if you still need to.

**Comment by dahendel** [comment]
Marking closed
