### ISSUE TITLE
awx_host needs enabled value in example

### ISSUE THREAD

**Issue by richardsonky** [dahendel/terraform-provider-awx2#2]
I'm testing out your provider (works great so far) but just wanted to make a suggestion for your example, add the "enabled" variable in the awx_host example so that the host is enabled when it is created.  Your example doesn't explain that.  I found it in the code though and turned it on.  Thanks for building this!

**Comment by dahendel** [comment]
@richardsonky Thanks for letting me know! I went ahead and added it into the example. Let me know if there is anything else
